import type * as Party from "partykit/server";

/**
 * ARC Lens Multi-Device Session Server
 *
 * Each PartyKit room represents a session between desktop (host) and mobile (viewer).
 * The room ID is the session ID generated by the desktop client.
 */
export default class SessionServer implements Party.Server {
  constructor(public party: Party.Party) {}

  // Track which connection is the host
  hostConnection: Party.Connection | null = null;
  viewerConnections: Set<Party.Connection> = new Set();

  /**
   * Called when a new client connects
   */
  async onConnect(connection: Party.Connection, ctx: Party.ConnectionContext) {
    console.log(
      `Client ${connection.id} connected to room ${this.party.id}`
    );

    // Send connection count to all clients
    this.broadcastConnectionStatus();
  }

  /**
   * Called when a message is received from a client
   */
  async onMessage(message: string | ArrayBuffer, sender: Party.Connection) {
    try {
      const data = typeof message === "string" ? JSON.parse(message) : null;
      if (!data) return;

      const { type, payload } = data;

      switch (type) {
        case "HOST_CREATE_SESSION":
          // Mark this connection as the host
          this.hostConnection = sender;
          sender.send(
            JSON.stringify({
              type: "CONNECTION_STATUS",
              payload: {
                status: "connected",
                role: "host",
                sessionId: this.party.id,
              },
            })
          );
          console.log(`Host connected to room ${this.party.id}`);
          this.broadcastConnectionStatus();
          break;

        case "VIEWER_JOIN_SESSION":
          // Mark this connection as a viewer
          this.viewerConnections.add(sender);
          sender.send(
            JSON.stringify({
              type: "CONNECTION_STATUS",
              payload: {
                status: "connected",
                role: "viewer",
                sessionId: this.party.id,
              },
            })
          );

          // Request initial state from host
          if (this.hostConnection) {
            this.hostConnection.send(
              JSON.stringify({
                type: "REQUEST_INITIAL_STATE",
                payload: { viewerSocketId: sender.id },
              })
            );
          }
          console.log(`Viewer ${sender.id} joined room ${this.party.id}`);
          this.broadcastConnectionStatus();
          break;

        case "SYNC_INITIAL":
        case "SYNC_ANALYSIS":
        case "SYNC_SETTINGS":
        case "SYNC_INVENTORY_STATE":
          // Broadcast to all other connections
          this.party.broadcast(
            JSON.stringify({ type, payload }),
            [sender.id] // Exclude sender
          );
          break;

        default:
          console.warn(`Unknown message type: ${type}`);
      }
    } catch (error) {
      console.error("Error handling message:", error);
    }
  }

  /**
   * Called when a client disconnects
   */
  async onClose(connection: Party.Connection) {
    console.log(`Client ${connection.id} disconnected from room ${this.party.id}`);

    // If host disconnects, end the session for everyone
    if (this.hostConnection === connection) {
      console.log(`Host disconnected from room ${this.party.id}, ending session`);
      this.party.broadcast(
        JSON.stringify({
          type: "SESSION_ENDED",
          payload: { reason: "host_disconnected" },
        })
      );
      this.hostConnection = null;
      this.viewerConnections.clear();
    } else {
      // Remove viewer
      this.viewerConnections.delete(connection);

      // Notify host
      if (this.hostConnection) {
        this.hostConnection.send(
          JSON.stringify({
            type: "VIEWER_DISCONNECTED",
            payload: { socketId: connection.id },
          })
        );
      }
    }

    this.broadcastConnectionStatus();
  }

  /**
   * Broadcast current connection status to all clients
   */
  broadcastConnectionStatus() {
    const status = {
      hostConnected: this.hostConnection !== null,
      viewerCount: this.viewerConnections.size,
    };

    this.party.broadcast(
      JSON.stringify({
        type: "CONNECTION_STATUS_UPDATE",
        payload: status,
      })
    );
  }

  /**
   * Called when the server starts (optional)
   */
  async onStart() {
    console.log(`Session server started for room ${this.party.id}`);
  }
}

// PartyKit will use this as the default export
SessionServer satisfies Party.Worker;
